# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Docker PaperMC Server
site_description: A comprehensive guide for setting up and managing a PaperMC server using Docker.
site_author: Djaytan
site_url: https://djaytan.github.io/docker-papermc-server/
copyright: Copyright © 2025 Djaytan

theme:
  name: material
  locale: en
  favicon: assets/logo.png
  logo: assets/logo-flat.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

nav:
  - Home: index.md
  - Usage: usage.md
  - Configuration:
      - General: configuration.md
      - Environment Variables: environment-variables.md
      - Configuration Files: configuration-files.md
  - Production-Grade Deployment: production-grade-deployment.md

markdown_extensions:
  - admonition

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Djaytan/docker-papermc-server
