# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Docker PaperMC Server
site_description: A comprehensive guide for setting up and managing a PaperMC server using Docker.
site_author: Djaytan
site_url: https://djaytan.github.io/docker-papermc-server/
copyright: >
  Copyright © 2025 Djaytan –
  <a href="#__consent">Change cookie settings</a>

docs_dir: src/

theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo-flat.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Usage: usage.md
  - Configuration:
      - General: configuration.md
      - Environment Variables: environment-variables.md
      - Configuration Files: configuration-files.md
  - Production-Grade Deployment: production-grade-deployment.md
  - License: license.md

markdown_extensions:
  - admonition

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-38B41053ZC
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Djaytan/docker-papermc-server
