apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermc-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: papermc-server
  template:
    metadata:
      labels:
        app: papermc-server
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 0
        runAsUser: 2
      containers:
        - image: djaytan/papermc-server:dev
          imagePullPolicy: Never
          name: papermc-server
          stdin: true
          tty: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
          resources:
            requests:
              ephemeral-storage: 10Gi
              cpu: "4"
              memory: 8Gi
            limits:
              ephemeral-storage: 10Gi
              cpu: "4"
              memory: 8Gi
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: 'true'
