name: papermc-server
namespace: default
eula: false

container:
  image: djaytan/papermc-server:dev
  resources:
    requests:
      ephemeralStorage: 10Gi
      cpu: 4
      memory: 8Gi
    limits:
      ephemeralStorage: 10Gi
      cpu: 4
      memory: 8Gi

service:
  ports:
    nodePort: 30000

healthChecks:
  # Liveness check frequency (in seconds)
  checkInterval: 10
  # Startup grace period (in seconds) before liveness probes kick in
  # Must be a multiple of checkInterval
  startupGracePeriod: 300  # default: 5 minutes
