name: CI

on:
  workflow_dispatch:
  push:
    branches: [main, '+.x', next, next-major, beta, alpha]
  pull_request:
    branches: [main, '+.x', next, next-major, beta, alpha]
  schedule:
    - cron: '16 5 * * *' # Every day at 05:16

permissions: {}

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    permissions:
      contents: read

    env:
      IMAGE_TAG: ${{ github.repository_owner }}/papermc-server:test

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: src/
          tags: ${{ env.IMAGE_TO_TEST }}
          pull: true # Ensure latest base images are used
          load: true # Load into daemon for test usage in next step
          build-args: |
            BASE_IMAGE=${{ matrix.baseImage }}
          cache-from: type=gha,scope=${{ matrix.variant }}
