apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 25565
      targetPort: 25565
      nodePort: {{ .Values.service.ports.nodePort }}
