name: Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  release-perform:
    name: Release - Perform
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    permissions:
      contents: write # Required to publish a GitHub release
      issues: write # Required to comment on released issues
      pull-requests: write # Required to comment on released pull requests

    steps:
      # Firewall rules:
      # -> "*.github.com": Standard interactions with GitHub
      # -> "objects.githubusercontent.com": Uploading of security reports
      # -> "raw.githubusercontent.com": Retrieve license file when building OCI image
      # -> "*.docker.io" & "*.docker.com": Standard interactions with Docker
      # -> "*.ubuntu.com": Standard interactions with Ubuntu APT repositories
      # -> "api.papermc.io": Dynamic retrieval of the PaperMC server
      # -> "mirror.gcr.io": Downloading of the Trivy security scanner
      # -> "api.nuget.org" & "registry.npmjs.org": Downloading semantic-release CLI
      - name: Harden runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            objects.githubusercontent.com:443
            raw.githubusercontent.com:443
            uploads.github.com:443
            index.docker.io:443
            registry-1.docker.io:443
            auth.docker.io:443
            production.cloudflare.docker.com:443
            archive.ubuntu.com:80
            security.ubuntu.com:80
            api.papermc.io:443
            api.nuget.org:443
            registry.npmjs.org:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0 # Required by semantic-release

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: lts/jod
          cache: npm
          cache-dependency-path: .github/semantic-release/package-lock.json

      - name: Install semantic-release
        working-directory: .github/semantic-release/
        run: npm clean-install

      - name: Login to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setup of QEMU x Buildx
      # Required for multi-arch builds (typically for ARM architecture support)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ROOT_PROJECT_DIR: ${{ github.workspace }}
        working-directory: .github/semantic-release/
        run: npx --no-install semantic-release
